import type { Metadata } from 'next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Poppins } from 'next/font/google';
import './globals.css';
import 'remixicon/fonts/remixicon.css';

import Header from './components/Header';
import Footer from './components/Footer';

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Code Pirates',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <Header />
        {children}
        <Footer />
        <SpeedInsights />
      </body>
    </html>
  );
}
